var lang_dict = {
    "cmn": { "lang": "Mandarin Chinese", "pop": "885" },
    "spa": { "lang": "Spanish", "pop": "332" },
    "eng": { "lang": "English", "pop": "322" },
    "rus": { "lang": "Russian", "pop": "288" },
    "arb": { "lang": "Arabic", "pop": "280" },
    "ben": { "lang": "Bengali", "pop": "196" },
    "hin": { "lang": "Hindi", "pop": "182" },
    "por": { "lang": "Portuguese", "pop": "182" },
    "ind": { "lang": "Indonesian", "pop": "140" },
    "jpn": { "lang": "Japanese", "pop": "125" },
    "fra": { "lang": "French", "pop": "124" },
    "deu": { "lang": "German", "pop": "121" },
    "jav": { "lang": "Javanese", "pop": "76" },
    "kor": { "lang": "Korean", "pop": "75" },
    "tel": { "lang": "Telugu", "pop": "73" },
    "vie": { "lang": "Vietnamese", "pop": "67" },
    "mar": { "lang": "Marathi", "pop": "65" },
    "ita": { "lang": "Italian", "pop": "63" },
    "tam": { "lang": "Tamil", "pop": "62" },
    "tur": { "lang": "Turkish", "pop": "59" },
    "urd": { "lang": "Urdu", "pop": "54" },
    "guj": { "lang": "Gujarati", "pop": "44" },
    "pol": { "lang": "Polish", "pop": "44" },
    "ukr": { "lang": "Ukrainian", "pop": "41" },
    "kan": { "lang": "Kannada", "pop": "38" },
    "mai": { "lang": "Maithili", "pop": "35" },
    "mal": { "lang": "Malayalam", "pop": "34" },
    "pes": { "lang": "Iranian Persian", "pop": "33" },
    "mya": { "lang": "Burmese", "pop": "31" },
    "swh": { "lang": "Swahili", "pop": "30" },
    "sun": { "lang": "Sundanese", "pop": "27" },
    "ron": { "lang": "Romanian", "pop": "26" },
    "pan": { "lang": "Panjabi", "pop": "26" },
    "bho": { "lang": "Bhojpuri", "pop": "25" },
    "amh": { "lang": "Amharic", "pop": "23" },
    "hau": { "lang": "Hausa", "pop": "22" },
    "fuv": { "lang": "Nigerian Fulfulde", "pop": "22" },
    "bos": { "lang": "Bosnian", "pop": "21" },
    "hrv": { "lang": "Croatian", "pop": "21" },
    "nld": { "lang": "Dutch", "pop": "21" },
    "srp": { "lang": "Serbian", "pop": "21" },
    "tha": { "lang": "Thai", "pop": "21" },
    "ckb": { "lang": "Kurdish", "pop": "20" },
    "yor": { "lang": "Yoruba", "pop": "20" },
    "uzn": { "lang": "Northern Uzbek", "pop": "18" },
    "zlm": { "lang": "Malay", "pop": "18" },
    "ibo": { "lang": "Igbo", "pop": "17" },
    "npi": { "lang": "Nepali", "pop": "16" },
    "ceb": { "lang": "Cebuano", "pop": "15" },
    "skr": { "lang": "Saraiki", "pop": "15" },
    "tgl": { "lang": "Tagalog", "pop": "15" },
    "hun": { "lang": "Hungarian", "pop": "15" },
    "azj": { "lang": "Azerbaijani", "pop": "14" },
    "sin": { "lang": "Sinhala", "pop": "13" },
    "koi": { "lang": "Komi-Permyak", "pop": "13" },
    "ell": { "lang": "Greek", "pop": "12" },
    "ces": { "lang": "Czech", "pop": "12" },
    "mag": { "lang": "Magahi", "pop": "11" },
    "run": { "lang": "Rundi", "pop": "11" },
    "bel": { "lang": "Belarusian", "pop": "10" },
    "plt": { "lang": "Plateau Malagasy", "pop": "10" },
    "qug": { "lang": "Chimborazo Highland Quichua", " pop": "10" },
    "mad": { "lang": "Madurese", "pop": "10" },
    "nya": { "lang": "Nyanja", "pop": "10" },
    "zyb": { "lang": "Yongbei Zhuang", "pop": "10" },
    "pbu": { "lang": "Northern Pashto", "pop": "10" },
    "kin": { "lang": "Kinyarwanda", "pop": "9" },
    "zul": { "lang": "Zulu", "pop": "9" },
    "bul": { "lang": "Bulgarian", "pop": "9" },
    "swe": { "lang": "Swedish", "pop": "9" },
    "lin": { "lang": "Lingala", "pop": "8" },
    "som": { "lang": "Somali", "pop": "8" },
    "hms": { "lang": "Southern Qiandong Miao", "pop": "8" },
    "hnj": { "lang": "Hmong Njua", "pop": "8" },
    "ilo": { "lang": "Iloko", "pop": "8" },
    "kaz": { "lang": "Kazakh", "pop": "8" }
};

// var black_list  = [];

// for (var key in lang_dict) {
//     if (lang_dict[key]['pop'] > 200) {
//         black_list.push(key);
//     }
// }